-- E-commerce Detail AI Workbench database schema

CREATE TABLE IF NOT EXISTS product_material (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    brand_id BIGINT COMMENT '品牌ID',
    brand_name VARCHAR(100) COMMENT '品牌名称',
    product_name VARCHAR(255) NOT NULL COMMENT '商品名称',
    product_sku VARCHAR(100) COMMENT '商品SKU',
    category VARCHAR(100) COMMENT '商品类目',
    price DECIMAL(10,2) COMMENT '商品价格',
    description TEXT COMMENT '商品描述',
    images JSON COMMENT '商品图片列表',
    videos JSON COMMENT '商品视频列表',
    documents JSON COMMENT '商品文档列表',
    status TINYINT DEFAULT 1 COMMENT '资料状态',
    original_file_path VARCHAR(500) COMMENT '原始文件路径',
    file_type VARCHAR(50) COMMENT '文件类型',
    file_size BIGINT COMMENT '文件大小',
    uploader VARCHAR(50) COMMENT '上传人',
    upload_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间',
    parse_status TINYINT DEFAULT 0 COMMENT '解析状态',
    parse_error TEXT COMMENT '解析错误信息',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标识',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_product_name (product_name),
    INDEX idx_product_sku (product_sku),
    INDEX idx_category (category),
    INDEX idx_brand_id (brand_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品资料表';

CREATE TABLE IF NOT EXISTS brand_template (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    brand_id BIGINT COMMENT '品牌ID',
    brand_name VARCHAR(100) COMMENT '品牌名称',
    template_name VARCHAR(100) NOT NULL COMMENT '模板名称',
    template_type VARCHAR(50) COMMENT '模板类型',
    template_content TEXT COMMENT '模板内容',
    style_tags VARCHAR(500) COMMENT '风格标签',
    style_description TEXT COMMENT '风格描述',
    applicable_categories VARCHAR(500) COMMENT '适用类目',
    enabled TINYINT(1) DEFAULT 1 COMMENT '是否启用',
    usage_count INT DEFAULT 0 COMMENT '使用次数',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标识',
    creator VARCHAR(50) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(50) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_brand_id (brand_id),
    INDEX idx_brand_name (brand_name),
    INDEX idx_template_name (template_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='品牌模板表';

CREATE TABLE IF NOT EXISTS product_detail (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    material_id BIGINT COMMENT '商品资料ID',
    product_name VARCHAR(255) COMMENT '商品名称',
    brand_id BIGINT COMMENT '品牌ID',
    brand_name VARCHAR(100) COMMENT '品牌名称',
    title VARCHAR(255) COMMENT '标题',
    subtitle VARCHAR(500) COMMENT '副标题',
    selling_points TEXT COMMENT '核心卖点列表',
    seo_keywords TEXT COMMENT 'SEO关键词列表',
    image_template_id BIGINT COMMENT '图片模板ID',
    sku VARCHAR(100) COMMENT '商品SKU',
    category VARCHAR(100) COMMENT '分类',
    price DECIMAL(10,2) COMMENT '价格',
    description TEXT COMMENT '描述',
    ai_generated_content TEXT COMMENT 'AI生成内容',
    images JSON COMMENT '图片列表',
    videos JSON COMMENT '视频列表',
    documents JSON COMMENT '文档列表',
    risk_level VARCHAR(20) COMMENT '风险等级',
    risk_description TEXT COMMENT '风险描述',
    audit_status TINYINT DEFAULT 0 COMMENT '审核状态',
    auditor VARCHAR(50) COMMENT '审核人',
    audit_time DATETIME COMMENT '审核时间',
    audit_comment TEXT COMMENT '审核意见',
    version INT DEFAULT 1 COMMENT '版本号',
    is_current_version TINYINT(1) DEFAULT 1 COMMENT '是否当前版本',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标识',
    creator VARCHAR(50) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(50) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_material_id (material_id),
    INDEX idx_product_name (product_name),
    INDEX idx_sku (sku),
    INDEX idx_brand_id (brand_id),
    INDEX idx_audit_status (audit_status),
    INDEX idx_risk_level (risk_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品详情页表';

CREATE TABLE IF NOT EXISTS audit_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    product_detail_id BIGINT NOT NULL COMMENT '商品详情页ID',
    audit_type VARCHAR(50) COMMENT '审核类型',
    audit_status TINYINT NOT NULL COMMENT '审核状态',
    risk_level TINYINT COMMENT '风险等级',
    risk_items TEXT COMMENT '风险项列表',
    audit_comment TEXT COMMENT '审核意见',
    modification_suggestions TEXT COMMENT '修改建议',
    submitter VARCHAR(50) COMMENT '提交人',
    submit_time DATETIME COMMENT '提交时间',
    auditor VARCHAR(50) COMMENT '审核人',
    audit_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '审核时间',
    audit_duration INT COMMENT '审核耗时',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标识',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_product_detail_id (product_detail_id),
    INDEX idx_audit_status (audit_status),
    INDEX idx_auditor (auditor),
    INDEX idx_audit_time (audit_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审核记录表';

CREATE TABLE IF NOT EXISTS export_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    product_detail_id BIGINT NOT NULL COMMENT '商品详情页ID',
    export_format VARCHAR(20) NOT NULL COMMENT '导出格式',
    file_path VARCHAR(500) COMMENT '导出文件路径',
    file_name VARCHAR(255) COMMENT '文件名',
    file_size BIGINT COMMENT '文件大小',
    export_status TINYINT DEFAULT 0 COMMENT '导出状态',
    error_message TEXT COMMENT '错误信息',
    exporter VARCHAR(50) COMMENT '导出人',
    export_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '导出时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标识',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_product_detail_id (product_detail_id),
    INDEX idx_export_status (export_status),
    INDEX idx_exporter (exporter),
    INDEX idx_export_time (export_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='导出记录表';
