package com.ecommerce.detail.ai.util;

import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.springframework.stereotype.Component;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

/**
 * 导出工具类
 * 提供多种格式的文档导出功能
 * 
 * @author Administrator
 * @version 1.0.0
 */
@Slf4j
@Component
public class ExportUtil {

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    private final FileUtil fileUtil;

    public ExportUtil(FileUtil fileUtil) {
        this.fileUtil = fileUtil;
    }

    /**
     * 导出为Word文档
     * 
     * @param content 内容
     * @param title 标题
     * @param outputPath 输出路径
     * @return 生成的文件路径
     */
    public String exportToWord(String content, String title, String outputPath) {
        try {
            String safeTitle = title == null || title.trim().isEmpty() ? "产品详情" : title.trim();
            String fileName = generateFileName(safeTitle, "docx");
            Path path = Paths.get(outputPath, fileName);
            Files.createDirectories(path.getParent());

            try (XWPFDocument document = new XWPFDocument();
                 OutputStream outputStream = Files.newOutputStream(path)) {
                XWPFParagraph titleParagraph = document.createParagraph();
                titleParagraph.setAlignment(ParagraphAlignment.CENTER);
                XWPFRun titleRun = titleParagraph.createRun();
                titleRun.setBold(true);
                titleRun.setFontSize(18);
                titleRun.setText(safeTitle);

                String normalizedContent = content == null ? "" : content;
                for (String line : normalizedContent.split("\\R", -1)) {
                    XWPFParagraph paragraph = document.createParagraph();
                    XWPFRun run = paragraph.createRun();
                    run.setFontSize(11);
                    run.setText(line);
                }

                document.write(outputStream);
            }

            String fullPath = path.toString();
            log.info("Word文档导出成功: {}", fullPath);
            
            return fullPath;
        } catch (Exception e) {
            log.error("导出Word文档失败", e);
            throw new RuntimeException("导出Word文档失败: " + e.getMessage(), e);
        }
    }

    /**
     * 导出为Markdown格式
     * 
     * @param content 内容
     * @param title 标题
     * @param outputPath 输出路径
     * @return 生成的文件路径
     */
    public String exportToMarkdown(String content, String title, String outputPath) {
        try {
            StringBuilder mdContent = new StringBuilder();
            mdContent.append("# ").append(title).append("\n\n");
            mdContent.append(content).append("\n\n");
            mdContent.append("---\n");
            mdContent.append("*Generated by Ecommerce Detail AI on ")
                    .append(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()))
                    .append("*\n");
            
            String fileName = generateFileName(title, "md");
            String fullPath = outputPath + "/" + fileName;
            
            fileUtil.writeTextFile(fullPath, mdContent.toString());
            log.info("Markdown文档导出成功: {}", fullPath);
            
            return fullPath;
        } catch (Exception e) {
            log.error("导出Markdown文档失败", e);
            throw new RuntimeException("导出Markdown文档失败: " + e.getMessage(), e);
        }
    }

    /**
     * 导出为HTML格式
     * 
     * @param content 内容
     * @param title 标题
     * @param outputPath 输出路径
     * @return 生成的文件路径
     */
    public String exportToHtml(String content, String title, String outputPath) {
        try {
            StringBuilder htmlContent = new StringBuilder();
            htmlContent.append("<!DOCTYPE html>\n");
            htmlContent.append("<html lang=\"zh-CN\">\n");
            htmlContent.append("<head>\n");
            htmlContent.append("  <meta charset=\"UTF-8\">\n");
            htmlContent.append("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
            htmlContent.append("  <title>").append(escapeHtml(title)).append("</title>\n");
            htmlContent.append("  <style>\n");
            htmlContent.append("    body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }\n");
            htmlContent.append("    h1 { color: #333; border-bottom: 2px solid #eee; padding-bottom: 10px; }\n");
            htmlContent.append("    .content { margin-top: 20px; }\n");
            htmlContent.append("    .footer { margin-top: 40px; color: #999; font-size: 12px; }\n");
            htmlContent.append("  </style>\n");
            htmlContent.append("</head>\n");
            htmlContent.append("<body>\n");
            htmlContent.append("  <h1>").append(escapeHtml(title)).append("</h1>\n");
            htmlContent.append("  <div class=\"content\">\n");
            htmlContent.append("    ").append(convertToHtmlParagraphs(content)).append("\n");
            htmlContent.append("  </div>\n");
            htmlContent.append("  <div class=\"footer\">\n");
            htmlContent.append("    <p>Generated by Ecommerce Detail AI on ")
                    .append(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()))
                    .append("</p>\n");
            htmlContent.append("  </div>\n");
            htmlContent.append("</body>\n");
            htmlContent.append("</html>");
            
            String fileName = generateFileName(title, "html");
            String fullPath = outputPath + "/" + fileName;
            
            fileUtil.writeTextFile(fullPath, htmlContent.toString());
            log.info("HTML文档导出成功: {}", fullPath);
            
            return fullPath;
        } catch (Exception e) {
            log.error("导出HTML文档失败", e);
            throw new RuntimeException("导出HTML文档失败: " + e.getMessage(), e);
        }
    }

    /**
     * 导出为JSON格式
     * 
     * @param data 数据对象
     * @param outputPath 输出路径
     * @return 生成的文件路径
     */
    public String exportToJson(Map<String, Object> data, String outputPath) {
        try {
            String jsonContent = OBJECT_MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(data);
            String fileName = "export_" + System.currentTimeMillis() + ".json";
            String fullPath = outputPath + "/" + fileName;
            
            fileUtil.writeTextFile(fullPath, jsonContent);
            log.info("JSON文档导出成功: {}", fullPath);
            
            return fullPath;
        } catch (Exception e) {
            log.error("导出JSON文档失败", e);
            throw new RuntimeException("导出JSON文档失败: " + e.getMessage(), e);
        }
    }

    /**
     * 导出为TXT纯文本格式
     * 
     * @param content 内容
     * @param title 标题
     * @param outputPath 输出路径
     * @return 生成的文件路径
     */
    public String exportToTxt(String content, String title, String outputPath) {
        try {
            StringBuilder txtContent = new StringBuilder();
            txtContent.append(title).append("\n");
            txtContent.append("=".repeat(title.length())).append("\n\n");
            txtContent.append(content).append("\n\n");
            txtContent.append("-".repeat(50)).append("\n");
            txtContent.append("生成时间: ").append(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date())).append("\n");
            txtContent.append("生成工具: Ecommerce Detail AI\n");
            
            String fileName = generateFileName(title, "txt");
            String fullPath = outputPath + "/" + fileName;
            
            fileUtil.writeTextFile(fullPath, txtContent.toString());
            log.info("TXT文档导出成功: {}", fullPath);
            
            return fullPath;
        } catch (Exception e) {
            log.error("导出TXT文档失败", e);
            throw new RuntimeException("导出TXT文档失败: " + e.getMessage(), e);
        }
    }

    /**
     * 导出为CSV格式
     * 
     * @param dataList 数据列表
     * @param headers 表头
     * @param outputPath 输出路径
     * @return 生成的文件路径
     */
    public String exportToCsv(java.util.List<String[]> dataList, String[] headers, String outputPath) {
        try {
            String fileName = "export_" + System.currentTimeMillis() + ".csv";
            String fullPath = outputPath + "/" + fileName;
            
            fileUtil.writeCSV(fullPath, dataList, headers);
            log.info("CSV文档导出成功: {}", fullPath);
            
            return fullPath;
        } catch (Exception e) {
            log.error("导出CSV文档失败", e);
            throw new RuntimeException("导出CSV文档失败: " + e.getMessage(), e);
        }
    }

    /**
     * 批量导出（支持多种格式）
     * 
     * @param content 内容
     * @param title 标题
     * @param formats 导出格式数组
     * @param outputPath 输出路径
     * @return 生成的文件路径数组
     */
    public String[] exportMultipleFormats(String content, String title, String[] formats, String outputPath) {
        java.util.List<String> filePaths = new java.util.ArrayList<>();
        
        for (String format : formats) {
            try {
                String path = null;
                switch (format.toUpperCase()) {
                    case "WORD":
                    case "DOCX":
                        path = exportToWord(content, title, outputPath);
                        break;
                    case "MARKDOWN":
                    case "MD":
                        path = exportToMarkdown(content, title, outputPath);
                        break;
                    case "HTML":
                    case "HTM":
                        path = exportToHtml(content, title, outputPath);
                        break;
                    case "TXT":
                    case "TEXT":
                        path = exportToTxt(content, title, outputPath);
                        break;
                    default:
                        log.warn("不支持的导出格式: {}", format);
                        continue;
                }
                
                if (path != null) {
                    filePaths.add(path);
                }
            } catch (Exception e) {
                log.error("导出格式 {} 失败", format, e);
            }
        }
        
        return filePaths.toArray(new String[0]);
    }

    /**
     * 生成文件名
     * 
     * @param title 标题
     * @param extension 扩展名
     * @return 文件名
     */
    private String generateFileName(String title, String extension) {
        String timestamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
        String safeTitle = title.replaceAll("[^a-zA-Z0-9\\u4e00-\\u9fa5]", "_");
        
        if (safeTitle.length() > 50) {
            safeTitle = safeTitle.substring(0, 50);
        }
        
        return safeTitle + "_" + timestamp + "." + extension;
    }

    /**
     * HTML转义
     * 
     * @param text 原始文本
     * @return 转义后的文本
     */
    private String escapeHtml(String text) {
        if (text == null) {
            return "";
        }
        return text.replace("&", "&amp;")
                  .replace("<", "&lt;")
                  .replace(">", "&gt;")
                  .replace("\"", "&quot;");
    }

    /**
     * 将文本转换为HTML段落
     * 
     * @param content 原始内容
     * @return HTML段落
     */
    private String convertToHtmlParagraphs(String content) {
        if (content == null || content.isEmpty()) {
            return "<p></p>";
        }
        
        String[] lines = content.split("\n");
        StringBuilder html = new StringBuilder();
        
        for (String line : lines) {
            if (!line.trim().isEmpty()) {
                html.append("    <p>").append(escapeHtml(line.trim())).append("</p>\n");
            }
        }
        
        return html.length() > 0 ? html.toString() : "<p></p>";
    }

    /**
     * 根据产品详情ID导出文档
     * 
     * @param productDetailId 产品详情ID
     * @param format 导出格式（WORD、MARKDOWN、HTML、TXT）
     * @return 生成的文件路径
     */
    public String exportProductDetailById(Long productDetailId, String format) {
        throw new UnsupportedOperationException("Export by id requires ProductDetail data. Use ExportService instead.");
    }

    /**
     * 导出产品详情文档
     * 
     * @param dto 产品详情DTO
     * @param template 品牌模板（可为null）
     * @param format 导出格式（WORD、MARKDOWN、JSON、HTML、TXT）
     * @return 生成的文件路径
     */
    public String exportProductDetail(com.ecommerce.detail.ai.dto.ProductDetailDTO dto,
                                     com.ecommerce.detail.ai.entity.BrandTemplate template,
                                     String format) {
        // 构建导出内容
        StringBuilder content = new StringBuilder();
        
        if (template != null) {
            content.append("# ").append(template.getTemplateName()).append("\n\n");
        }
        
        content.append("## 商品信息\n");
        content.append("- 商品名称: ").append(dto.getProductName()).append("\n");
        content.append("- SKU: ").append(dto.getSku()).append("\n");
        content.append("- 分类: ").append(dto.getCategory()).append("\n");
        content.append("- 价格: ").append(dto.getPrice()).append("\n\n");
        
        if (dto.getDescription() != null && !dto.getDescription().isEmpty()) {
            content.append("## 商品描述\n").append(dto.getDescription()).append("\n\n");
        }
        
        if (dto.getAiGeneratedContent() != null && !dto.getAiGeneratedContent().isEmpty()) {
            content.append("## AI生成内容\n").append(dto.getAiGeneratedContent()).append("\n\n");
        }
        
        String title = dto.getProductName() != null ? dto.getProductName() : "产品详情";
        String outputPath = "exports";
        fileUtil.createDirectory(outputPath);

        com.ecommerce.detail.ai.common.enums.ExportFormat exportFormat =
                com.ecommerce.detail.ai.common.enums.ExportFormat.fromValue(format);
        if (!exportFormat.isImplemented()) {
            throw new UnsupportedOperationException("PDF导出尚未实现，已阻止降级生成TXT文件");
        }
        switch (exportFormat) {
            case WORD:
                return exportToWord(content.toString(), title, outputPath);
            case MARKDOWN:
                return exportToMarkdown(content.toString(), title, outputPath);
            case JSON:
                return exportToJson(buildExportData(dto, template), outputPath);
            case HTML:
                return exportToHtml(content.toString(), title, outputPath);
            case TXT:
                return exportToTxt(content.toString(), title, outputPath);
            default:
                throw new IllegalArgumentException("Unsupported export format: " + format);
        }
    }

    private Map<String, Object> buildExportData(com.ecommerce.detail.ai.dto.ProductDetailDTO dto,
                                                com.ecommerce.detail.ai.entity.BrandTemplate template) {
        Map<String, Object> data = new LinkedHashMap<>();
        data.put("productId", dto.getProductId());
        data.put("materialId", dto.getMaterialId());
        data.put("brandId", dto.getBrandId());
        data.put("productName", dto.getProductName());
        data.put("sku", dto.getSku());
        data.put("category", dto.getCategory());
        data.put("price", dto.getPrice());
        data.put("description", dto.getDescription());
        data.put("title", dto.getTitle());
        data.put("subtitle", dto.getSubtitle());
        data.put("sellingPoints", dto.getSellingPoints());
        data.put("seoKeywords", dto.getSeoKeywords());
        data.put("aiGeneratedContent", dto.getAiGeneratedContent());
        if (template != null) {
            data.put("templateId", template.getId());
            data.put("templateName", template.getTemplateName());
        }
        data.put("exportedAt", new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));
        return data;
    }
}
